export const TYPES = {
   FETCH_MYFOODLIST_REQUEST: 'FETCH_MY_FOOD_LIST_REQUEST',
   FETCH_MYFOODLIST_SUCCESS: 'FETCH_MY_FOOD_LIST_SUCCESS',

   FETCH_FOODSAVELIST_REQUEST: 'FETCH_FOOD_SAVE_LIST_REQUEST',
   FETCH_FOODSAVELIST_SUCCESS: 'FETCH_FOOD_SAVE_LIST_SUCCESS',

   FETCH_NEWFOODLIST_REQUEST: 'FETCH_NEW_FOOD_LIST_REQUEST',
   FETCH_NEWFOODLIST_SUCCESS: 'FETCH_NEW_FOOD_LIST_SUCCESS',

   FETCH_SETFOODLIST_REQUEST: 'FETCH_SET_FOOD_LIST_REQUEST',
   FETCH_SETFOODLIST_SUCCESS: 'FETCH_SET_FOOD_LIST_SUCCESS',

   FETCH_SPECIALFOODLIST_REQUEST: 'FETCH_SPECIAL_FOOD_LIST_REQUEST',
   FETCH_SPECIALFOODLIST_SUCCESS: 'FETCH_SPECIAL_FOOD_LIST_SUCCESS',

   FETCH_TOPFOODLIST_REQUEST: 'FETCH_TOP_FOOD_LIST_REQUEST',
   FETCH_TOPFOODLIST_SUCCESS: 'FETCH_TOP_FOOD_LIST_SUCCESS',

   ADD_RATE_LIST_FOOD: 'ADD_RATE_LIST_FOOD'
  };
  