export const TYPES = {
    ADDFOOD_REQUEST: 'ADD_FOOD_REQUEST',
    ADDFOOD_SUCCESS: 'ADD_FOOD_SUCCESS',

    UPLOAD_IMAGE_REQUEST: 'UPLOAD_IMAGE_REQUEST',
    UPLOAD_IMAGE_SUCCESS: 'UPLOAD_IMAGE_SUCCESS',
  };
  